
pipeline {
    agent {
        node { label 'master'}
    }
	stages {
        stage('sample one'){
            steps{
                script {
                   sh 'echo "hello world"'
				}
			}
		}
		stage('Checkout code') {
			steps {
				sh 'echo "bolo"'
			}
		}
		
	}
}